name: 'GitHub Action for SwiftLint'
description: 'A tool to enforce Swift style and conventions. Forked from norio-nomura/action-swiftlint.'
author: 'Jeremy Klein <jklein24>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'
  color: 'orange'
